/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CounterMain: typeof import('./src/components/CounterMain.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Header: typeof import('./src/components/Organisms/Header.vue')['default']
    PrinterCard: typeof import('./src/components/Atoms/PrinterCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/Organisms/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/Organisms/TheHeader.vue')['default']
    TheWelcome: typeof import('./src/components/Atoms/TheWelcome.vue')['default']
    ThreadLengthInput: typeof import('./src/components/Atoms/ThreadLengthInput.vue')['default']
  }
}
