/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoilCard: typeof import('./src/components/Atoms/CoilCard.vue')['default']
    CoilForm: typeof import('./src/components/Organisms/CoilForm.vue')['default']
    CoilList: typeof import('./src/components/Organisms/CoilList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ModelCard: typeof import('./src/components/Atoms/ModelCard.vue')['default']
    ModelList: typeof import('./src/components/Organisms/ModelList.vue')['default']
    PrinterCard: typeof import('./src/components/Atoms/PrinterCard.vue')['default']
    PrinterList: typeof import('./src/components/Organisms/PrinterList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/Organisms/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/Organisms/TheHeader.vue')['default']
    ThreadLengthInput: typeof import('./src/components/Atoms/ThreadLengthInput.vue')['default']
  }
}
